<a href="https://colab.research.google.com/github/poojakanchala/Edukroncodes7781/blob/main/Banking_questions_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Question 1: Array Creation and Manipulation

In [1]:
# Q1.1: Create a 4x4 identity matrix using np.eye()
import numpy as np
Identity_matrix = np.eye(4)
print(Identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [2]:
# Q1.2: Create an array of 8 zeros using np.zeros()
array_zeros = np.zeros(8)
print(array_zeros)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
# Q1.3: Create an array of 6 ones using np.ones()
array_ones = np.ones(6)
print(array_ones)

[1. 1. 1. 1. 1. 1.]


In [5]:
# Q1.4: Create an array with values from 0 to 15 using np.arange()
array = np.arange(0,16)
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [6]:
# Q1.5: Create an array with 8 evenly spaced values from 0 to 100 using np.linspace()
array = np.linspace(0,100,8)
print(array)

[  0.          14.28571429  28.57142857  42.85714286  57.14285714
  71.42857143  85.71428571 100.        ]


In [ ]:
# Question 2: Array Attributes and Information

In [9]:
# Q2.1: What is the shape of the banking_data array?
banking_data = np.array([
    # Customer_ID, Account_Balance, Credit_Score, Transaction_Count, Years_Active
    [1, 25000, 300, 1200, 10],
    [2, 32000, 450, 1500, 15],
    [3, 28000, 380, 1100, 8],
    [4, 41000, 500, 1600, 20],
    [5, 35000, 420, 1400, 12],
    [6, 27000, 360, 1300, 9],
    [7, 39000, 480, 1700, 18],
    [8, 30000, 400, 1250, 14],
    [9, 45000, 550, 1800, 25],
    [10, 33000, 410, 1450, 11]
])

print(banking_data)

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


In [11]:
# Q2.2: What is the data type of the banking_data array?
print(type(banking_data))

<class 'numpy.ndarray'>


In [15]:
# Q2.3: What is the size (total number of elements) of the banking_data array?
banking_data_size = np.size(banking_data)
print(banking_data_size)

50


In [17]:
# Q2.4: What is the number of dimensions of the banking_data array?
dim_banking_data = np.ndim(banking_data)
print(dim_banking_data)

2


In [25]:
# Q2.5: What is the memory size of the banking_data array in bytes?
print(banking_data.nbytes)

400


In [ ]:
# Question 3: Indexing and Slicing

In [26]:
# Q3.1: Extract the first row of banking_data
print(banking_data[0])

[    1 25000   300  1200    10]


In [27]:
# Q3.2: Extract the last row of banking_data
print(banking_data[-1])

[   10 33000   410  1450    11]


In [28]:
# Q3.3: Extract the Account_Balance column (column index 1)
print(banking_data[:,1])

[25000 32000 28000 41000 35000 27000 39000 30000 45000 33000]


In [33]:
# Q3.4: Extract the first 4 rows and first 3 columns
print(banking_data[:4,:3])

[[    1 25000   300]
 [    2 32000   450]
 [    3 28000   380]
 [    4 41000   500]]


In [35]:
# Q3.5: Extract rows 3 to 7 (inclusive)
print(banking_data[3:8,:])

[[    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]]


In [ ]:
# Question 4: Mathematical Operations

In [36]:
# Q4.1: Calculate the sum of all account balances
sum_account = np.sum(banking_data[:,1])
print(sum_account)


335000


In [37]:
# Q4.2: Calculate the mean account balance
mean_account = np.mean(banking_data[:,1])
print(mean_account)

33500.0


In [38]:
# Q4.3: Calculate the standard deviation of account balances
std_account = np.std(banking_data[:,1])
print(std_account)

6168.468205316454


In [41]:
# Q4.4: Calculate the variance of account balances
var_account = np.var(banking_data[:,1])
print(var_account)

38050000.0


In [39]:
# Q4.5: Calculate the median account balance
median_account = np.median(banking_data[:,1])
print(median_account)

32500.0


In [ ]:
# Question 5: Statistical Functions

In [42]:
# Q5.1: Find the minimum and maximum account balances
min_account = np.min(banking_data[:,1])
max_account = np.max(banking_data[:,1])
print(f"min_account:{min_account},max_account:{max_account}")

min_account:25000,max_account:45000


In [45]:
# Q5.2: Find the minimum and maximum credit scores
min_Credit = np.min(banking_data[:,2])
max_Credit = np.max(banking_data[:,2])
print(f"min_Credit:{min_Credit},max_Credit:{max_Credit}")

min_Credit:300,max_Credit:550


In [48]:
# Q5.3: Calculate the percentile values for account balances (25th, 50th, 75th)
per_values = np.percentile(banking_data[:,1],[25,50,75])
print(per_values[0],per_values[1],per_values[2])

28500.0 32500.0 38000.0


In [50]:
# Q5.4: Calculate the correlation between account balance and credit score
cor_relation = np.corrcoef(banking_data[:,1],banking_data[:,2])[0,1]
print(cor_relation)

0.9593636912502479


In [53]:
# Q5.5: Calculate the covariance between account balance and credit score
covar = np.cov(banking_data[:,1],banking_data[:,2])[0,1]
print(covar)

453888.8888888889


In [ ]:
# Question 6: Array Reshaping and Manipulation

In [55]:
# Q6.1: Reshape the banking_data to 5 rows × 10 columns
reshaping_bdata = np.reshape(banking_data,(5,10))
print(reshaping_bdata)

[[    1 25000   300  1200    10     2 32000   450  1500    15]
 [    3 28000   380  1100     8     4 41000   500  1600    20]
 [    5 35000   420  1400    12     6 27000   360  1300     9]
 [    7 39000   480  1700    18     8 30000   400  1250    14]
 [    9 45000   550  1800    25    10 33000   410  1450    11]]


In [57]:
# Q6.2: Flatten the banking_data to a 1D array
flattening_bdata = banking_data.flatten()
print(flattening_bdata)

[    1 25000   300  1200    10     2 32000   450  1500    15     3 28000
   380  1100     8     4 41000   500  1600    20     5 35000   420  1400
    12     6 27000   360  1300     9     7 39000   480  1700    18     8
 30000   400  1250    14     9 45000   550  1800    25    10 33000   410
  1450    11]


In [58]:
# Q6.3: Transpose the banking_data
trans = banking_data.T
print(trans)

[[    1     2     3     4     5     6     7     8     9    10]
 [25000 32000 28000 41000 35000 27000 39000 30000 45000 33000]
 [  300   450   380   500   420   360   480   400   550   410]
 [ 1200  1500  1100  1600  1400  1300  1700  1250  1800  1450]
 [   10    15     8    20    12     9    18    14    25    11]]


In [63]:
# Q6.4: Split the banking_data into 2 equal parts vertically
split_bd = np.vsplit(banking_data,2)
print(split_bd[0])
print(split_bd[1])

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]]
[[    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


In [65]:
# Q6.5: Split the banking_data into 2 equal parts horizontally
# split_bd = np.hsplit(banking_data,2)
# print(split_bd[0])

In [ ]:
# Question 7: Logical Operations and Filtering

In [70]:
# Q7.1: Find customers with account balance greater than $100,000
data = banking_data[banking_data[:,1]> 100000]
print(data)


[]


In [71]:
# Q7.2: Find customers with credit score greater than 800
data = banking_data[banking_data[:,2]> 800]
print(data)

[]


In [8]:

import numpy as np
banking_data = np.array([
    # Customer_ID, Account_Balance, Credit_Score, Transaction_Count, Years_Active
    [1, 25000, 300, 1200, 10],
    [2, 32000, 450, 1500, 15],
    [3, 28000, 380, 1100, 8],
    [4, 41000, 500, 1600, 20],
    [5, 35000, 420, 1400, 12],
    [6, 27000, 360, 1300, 9],
    [7, 39000, 480, 1700, 18],
    [8, 30000, 400, 1250, 14],
    [9, 45000, 550, 1800, 25],
    [10, 33000, 410, 1450, 11]
])

print(banking_data)

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


In [5]:
# # Q7.3: Find customers with transaction count greater than 50 AND credit score less than 750
data = banking_data[(banking_data[:,3] > 50) & (banking_data[:,2] < 750)]
print(data)


[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


In [8]:
# Q7.4: Count how many customers have account balance between $10,000 and $100,000
data = np.sum((banking_data[:,1]>=10000) & (banking_data[:,1] <=100000))
print(data)


10


In [10]:
# Q7.5: Find the index of the customer with the highest credit score
data = np.argmax(banking_data[:,2])+1
print(data)

9


In [ ]:
# Question 8: Sorting and Searching

In [13]:
# Q8.1: Sort the banking_data by account balance (ascending)
data = banking_data[banking_data[:,1].argsort()]
data

array([[    1, 25000,   300,  1200,    10],
       [    6, 27000,   360,  1300,     9],
       [    3, 28000,   380,  1100,     8],
       [    8, 30000,   400,  1250,    14],
       [    2, 32000,   450,  1500,    15],
       [   10, 33000,   410,  1450,    11],
       [    5, 35000,   420,  1400,    12],
       [    7, 39000,   480,  1700,    18],
       [    4, 41000,   500,  1600,    20],
       [    9, 45000,   550,  1800,    25]])

In [15]:
# Q8.2: Sort the banking_data by credit score (descending)
data = banking_data[(-banking_data[:,2]).argsort()]
print(data)

[[    9 45000   550  1800    25]
 [    4 41000   500  1600    20]
 [    7 39000   480  1700    18]
 [    2 32000   450  1500    15]
 [    5 35000   420  1400    12]
 [   10 33000   410  1450    11]
 [    8 30000   400  1250    14]
 [    3 28000   380  1100     8]
 [    6 27000   360  1300     9]
 [    1 25000   300  1200    10]]


In [16]:
# Q8.3: Find the indices that would sort the array by years active
data = np.argsort(banking_data[:,4])
print(data)

[2 5 0 9 4 7 1 6 3 8]


In [28]:
# Q8.4: Find the customer with the second highest account balance
data1 = np.argsort(banking_data[:,1])[-2]
data = banking_data[data1]
print(data[0])



4


In [27]:
# Q8.5: Find the customer with the lowest transaction count
data1 = np.argmin(banking_data[:,3])
print(data[0])

3


In [ ]:
# Question 9: Mathematical Functions


In [29]:
# Q9.1: Calculate the absolute values of all elements
data = np.abs(banking_data)
print(data)


[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


In [30]:
# Q9.2: Calculate the square root of all account balances
data = np.sqrt(banking_data[:,1])
print(data)

[158.11388301 178.8854382  167.33200531 202.48456731 187.08286934
 164.31676725 197.48417658 173.20508076 212.13203436 181.65902125]


In [31]:
# Q9.3: Calculate the square of all credit scores
data = np.square(banking_data[:,2])
print(data)


[ 90000 202500 144400 250000 176400 129600 230400 160000 302500 168100]


In [33]:
# Q9.4: Calculate the exponential of all transaction counts
data = np.exp(banking_data[:,3])
print(data)

[inf inf inf inf inf inf inf inf inf inf]


/tmp/ipython-input-3198135566.py:2: RuntimeWarning: overflow encountered in exp
  data = np.exp(banking_data[:,3])


In [34]:
# Q9.5: Calculate the natural logarithm of all account balances
data = np.log(banking_data[:,1])
print(data)

[10.1266311  10.37349118 10.23995979 10.62132735 10.46310334 10.20359214
 10.57131693 10.30895266 10.71441777 10.40426284]


In [ ]:
# Question 10: Advanced Operations


In [35]:
# Q10.1: Calculate the cumulative sum of account balances
data = np.cumsum(banking_data[:,1])
print(data)


[ 25000  57000  85000 126000 161000 188000 227000 257000 302000 335000]


In [36]:
# Q10.2: Calculate the cumulative product of transaction counts
data = np.cumprod(banking_data[:,3])
print(data)


[                1200              1800000           1980000000
        3168000000000     4435200000000000  5765760000000000000
  6570896860228091904  4819962484364410880  5962757212450324480
 -5525012516809211904]


In [37]:
# Q10.3: Calculate the difference between consecutive account balances
data = np.diff(banking_data[:,1])
print(data)


[  7000  -4000  13000  -6000  -8000  12000  -9000  15000 -12000]


In [38]:
# Q10.4: Calculate the gradient of account balances
data = np.gradient(banking_data[:,1])
print(data)

[  7000.   1500.   4500.   3500.  -7000.   2000.   1500.   3000.   1500.
 -12000.]


In [39]:
# Q10.5: Calculate the histogram of account balances with 5 bins
hist,hist_bins = np.histogram(banking_data[:,1], bins = 5)
print(hist)
print(hist_bins)

[3 2 2 1 2]
[25000. 29000. 33000. 37000. 41000. 45000.]


In [ ]:
# Question 11: Random Numbers and Simulation

In [2]:
# Q11.1: Generate 6 random integers between 1 and 1000
import numpy as np
data = np.random.randint(1,1001,6)
print(data)

[486 254  36 598 398 860]


In [5]:
# Q11.2: Generate 6 random floats between 0 and 1
data = np.random.random(6)
print(data)

[0.97821559 0.52910989 0.73464533 0.56238228 0.47822868 0.72592818]


In [6]:
# Q11.3: Generate 6 random numbers from normal distribution (mean=700, std=100)
data = np.random.normal(700,100,6)
print(data)

[692.04048    846.51909728 661.72663364 661.23829855 670.73888303
 926.48790347]


In [9]:
# Q11.4: Shuffle the banking_data rows randomly
shuffled_data = banking_data.copy()
np.random.shuffle(shuffled_data)
print(shuffled_data)


[[    9 45000   550  1800    25]
 [    8 30000   400  1250    14]
 [    3 28000   380  1100     8]
 [    5 35000   420  1400    12]
 [    7 39000   480  1700    18]
 [    4 41000   500  1600    20]
 [   10 33000   410  1450    11]
 [    1 25000   300  1200    10]
 [    6 27000   360  1300     9]
 [    2 32000   450  1500    15]]


In [10]:
# Q11.5: Set random seed to 123 and generate 4 random numbersdata
np.random.seed(123)
seeded_random = np.random.random(4)
print(seeded_random)

[0.69646919 0.28613933 0.22685145 0.55131477]


In [ ]:
# Question 12: Linear Algebra Operations


In [12]:
# Q12.1: Calculate the dot product of account balance and credit score columns
dot_product = np.dot(banking_data[:, 1], banking_data[:, 2])
print(dot_product)


146460000


In [15]:
# Q12.2: Calculate the cross product of first two rows
cross_product = np.cross(banking_data[0, :3], banking_data[1, :3])
print(cross_product)

[1650000     150  -18000]


In [16]:
# Q12.3: Calculate the norm (magnitude) of the account balance column
banking_data = np.linalg.norm(banking_data[:, 1])
print(data)


[692.04048    846.51909728 661.72663364 661.23829855 670.73888303
 926.48790347]


In [18]:
# Q12.4: Create a 3x3 matrix and calculate its determinant
matrix_3x3 = np.array([[2, 3, 4], [1, 4, 8], [6, 7, 3]])
determinant = np.linalg.det(matrix_3x3)
print(matrix_3x3)
print(determinant)

[[2 3 4]
 [1 4 8]
 [6 7 3]]
-20.99999999999999


In [19]:
# Q12.5: Calculate the inverse of the 3x3 matrix
data = np.linalg.inv(matrix_3x3)
print(data)

[[ 2.0952381  -0.9047619  -0.38095238]
 [-2.14285714  0.85714286  0.57142857]
 [ 0.80952381 -0.19047619 -0.23809524]]


In [ ]:
# Question 13: String Operations


In [3]:
# Q2.1: What is the shape of the banking_data array?
banking_data = np.array([
    # Customer_ID, Account_Balance, Credit_Score, Transaction_Count, Years_Active
    [1, 25000, 300, 1200, 10],
    [2, 32000, 450, 1500, 15],
    [3, 28000, 380, 1100, 8],
    [4, 41000, 500, 1600, 20],
    [5, 35000, 420, 1400, 12],
    [6, 27000, 360, 1300, 9],
    [7, 39000, 480, 1700, 18],
    [8, 30000, 400, 1250, 14],
    [9, 45000, 550, 1800, 25],
    [10, 33000, 410, 1450, 11]
])

print(banking_data)

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


In [27]:
# Q13.1: Convert all customer IDs to strings
customer_ids_str = banking_data[:, 0].astype(str)
print(customer_ids_str)


['1' '2' '3' '4' '5' '6' '7' '8' '9' '10']


In [30]:
# Q13.2: Check if any customer ID contains '100'
data = np.char.find(customer_ids_str, '100') >= 0
print(banking_data[data])


[]


In [31]:
# Q13.3: Convert all customer IDs to uppercase (if they were strings)
data = np.char.upper(customer_ids_str)
print(data)

['1' '2' '3' '4' '5' '6' '7' '8' '9' '10']


In [32]:
# Q13.4: Count the length of each customer ID string
data = np.char.str_len(customer_ids_str)
print(data)


[1 1 1 1 1 1 1 1 1 2]


In [34]:
# Q13.5: Replace '10' with 'CUST' in customer IDs
data = np.char.replace(customer_ids_str, '10', 'CUST')
print(data)

['1' '2' '3' '4' '5' '6' '7' '8' '9' 'CUST']


In [ ]:
# Question 14: Date and Time Operations


In [35]:
# Q14.1: Convert years active to months
yrs_to_months = banking_data[:, 4] * 12
print(yrs_to_months)


[120 180  96 240 144 108 216 168 300 132]


In [36]:
# Q14.2: Calculate the average years active
avg_yrs = np.mean(banking_data[:, 4])
print(avg_yrs)


14.2


In [38]:
# Q14.3: Find customers who have been active for more than 15 years
yrs_active = banking_data[banking_data[:, 4] > 15]
print(yrs_active)


[[    4 41000   500  1600    20]
 [    7 39000   480  1700    18]
 [    9 45000   550  1800    25]]


In [39]:
# Q14.4: Calculate the total time all customers have been active (in years)
total_active_time = np.sum(banking_data[:, 4])
print(total_active_time)


142


In [41]:
# Q14.5: Find the customer with the shortest time active
customer_short_active= np.argmin(banking_data[:, 4])
shortest_customer_active = banking_data[customer_short_active]
print(f"customer ID: {customer_short_active}, Days: {shortest_customer_active}")

customer ID: 2, Days: [    3 28000   380  1100     8]


In [ ]:
# Question 15: Advanced Array Operations


In [4]:
# # Q15.1: Apply a function to calculate 5% interest on all account balances
# import numpy as np
# def add_interest(balance):
#   balance * 1.05
# interest_applied = np.vectorize(add_interest)(banking_data[:,1])
# print(interest_applied)

[None None None None None None None None None None]


In [9]:
# Q15.2: Use np.where to categorize customers by balance ranges
balances = banking_data[:,1]
customers_balance =  np.where(balances < 15000, "Low",
              np.where(balances < 45000, "Medium", "High"))
print(customers_balance)


['Medium' 'Medium' 'Medium' 'Medium' 'Medium' 'Medium' 'Medium' 'Medium'
 'High' 'Medium']


In [11]:
# Q15.3: Use np.select to categorize customers by credit score ranges
conditions = [
    banking_data[:, 4] < 9,
    (banking_data[:, 4] >= 15) & (banking_data[:, 4] < 20),
    banking_data[:, 4] >= 20
]
choices = ['poor', 'Mid-range', 'good']
cus_credit_score = np.select(conditions, choices, default='Unknown')
print(cus_credit_score)


['Unknown' 'Mid-range' 'poor' 'good' 'Unknown' 'Unknown' 'Mid-range'
 'Unknown' 'good' 'Unknown']


In [12]:
# Q15.4: Use np.piecewise to apply different interest rates based on balance
def low_interest(x): return x * 1.05
def mid_interest(x): return x * 1.10
def high_interest(x): return x * 1.20

interest_prices = np.piecewise(
    banking_data[:, 1],
    [banking_data[:, 1] < 20000, (banking_data[:, 1] >= 20000) & (banking_data[:, 1] < 25000), banking_data[:, 1] >= 25000],
    [low_interest, mid_interest, high_interest]
)
print(interest_prices)


[30000 38400 33600 49200 42000 32400 46800 36000 54000 39600]


In [13]:
# Q15.5: Use np.apply_along_axis to calculate the sum of each row
row_sums = np.apply_along_axis(np.sum, 1, banking_data)
print(row_sums)

[26511 33967 29491 43124 36837 28675 41205 31672 47384 34881]


In [ ]:
# Question 16: Array Concatenation and Stacking


In [3]:
# Q16.1: Concatenate two arrays horizontally using np.hstack()
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
con_array = np.hstack([array1,array2])
print(con_array)


[1 2 3 4 5 6]


In [15]:
# Q16.2: Concatenate two arrays vertically using np.vstack()
vcon_array = np.vstack([array1,array2])
print(vcon_array)


[[1 2 3]
 [4 5 6]]


In [19]:
# Q16.3: Concatenate arrays along a specific axis using np.concatenate()
import numpy as np
data = np.concatenate([array1,array2],axis = 0)
print(data)


[1 2 3 4 5 6]


In [21]:
# Q16.4: Stack arrays depth-wise using np.dstack()
data = np.dstack([array1,array2])
print(data)


[[[1 4]
  [2 5]
  [3 6]]]


In [22]:
# Q16.5: Create a column stack using np.column_stack()
data = np.column_stack([array1,array2])
print(data)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# Question 17: Array Splitting Operations


In [24]:
# Q17.1: Split an array into 3 equal parts using np.split()
array = np.array([1,2,3,4,5,6])
split_array = np.split(array,3)
for i, part in enumerate(split_array):
  print(f"Parts[{i+1}] = {part} ")


Parts[1] = [1 2] 
Parts[2] = [3 4] 
Parts[3] = [5 6] 


In [27]:
# Q17.2: Split an array at specific indices using np.split()
array = np.array([1,2,3,4,5,6])
split_array = np.split(array,[2,8])
print(split_array)


[array([1, 2]), array([3, 4, 5, 6]), array([], dtype=int64)]


In [31]:
# Q17.3: Split an array horizontally using np.hsplit()
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
hsplit_parts = np.hsplit(arr_2d, 3)
print(hsplit_parts)


[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [34]:
# Q17.4: Split an array vertically using np.vsplit()
vsplit_parts = np.vsplit(arr_2d, 2)
print(f"Vertical parts:{vsplit_parts}")


Vertical parts:[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [35]:
# Q17.5: Split an array into equal chunks using np.array_split()
chunks = np.array_split(array, 4)
print(f"Split into 4 chunks:{chunks}")

Split into 4 chunks:[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [ ]:
# Question 18: Array Repetition and Tiling


In [4]:
# Q18.1: Repeat each element of an array 3 times using np.repeat()
import numpy as np
elements = np.repeat(array1,3)
print(elements)


[1 1 1 2 2 2 3 3 3]


In [5]:
# Q18.2: Repeat an entire array 2 times using np.tile()
elements = np.tile(array1,2)
print(elements)



[1 2 3 1 2 3]


In [6]:
# Q18.3: Repeat a 2D array using np.tile()
arr_2d_small = np.array([[1, 2], [3, 4]])
tiled_2d = np.tile(arr_2d_small, (2, 3))
print(tiled_2d)

[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]


In [7]:
# Q18.4: Create a pattern using np.tile()
pattern = np.array([1, 0])
pattern_tiled = np.tile(pattern, 5)
print(pattern_tiled)

[1 0 1 0 1 0 1 0 1 0]


In [9]:
# Q18.5: Repeat elements with different counts using np.repeat()
repeat_counts = [2, 1, 3]
repeated_variable = np.repeat(array1, repeat_counts)
print(repeated_variable)

[1 1 2 3 3 3]


In [ ]:
# Question 19: Array Comparison and Logical Operations


In [10]:
# Q19.1: Compare two arrays for equality using np.array_equal()
out_comparision = np.array_equal(array1, array2)
print(out_comparision)


False


In [12]:
# Q19.2: Check if arrays are close using np.allclose()
close_comparision = np.allclose(array1, array2)
print(close_comparision)


False


In [14]:
# Q19.3: Apply logical AND operation between arrays
out_comparision = np.logical_and(array1>1, array2>4)
print(out_comparision)


[False  True  True]


In [15]:
# Q19.4: Apply logical OR operation between arrays
logical_or = np.logical_or(array1 == 1, array2 == 3)
print(logical_or)


[ True False False]


In [16]:
# Q19.5: Apply logical NOT operation to an array
logical_not = np.logical_not(array1 == 1)
print(logical_not)

[False  True  True]


In [ ]:
# Question 20: Array Set Operations


In [17]:
# Q20.1: Find unique elements in an array using np.unique()
array = np.array([1,1,3,2,5,3,5,5,7])
unique_ele = np.unique([array])
print(unique_ele)


[1 2 3 5 7]


In [20]:
# Q20.2: Find the intersection of two arrays using np.intersect1d()
intersection_ele = np.intersect1d(array1,array2)
print(intersection_ele)

[]


In [21]:
# Q20.3: Find the union of two arrays using np.union1d()
union_ele = np.union1d(array1,array2)
print(union_ele)


[1 2 3 4 5 6]


In [22]:
# Q20.4: Find elements in first array but not in second using np.setdiff1d()
ele_1st_notin_2nd = np.setdiff1d(array1,array2)
print(ele_1st_notin_2nd)

[1 2 3]


In [23]:
# Q20.5: Find the symmetric difference between two arrays using np.setxor1d()
symmetric_diff = np.setxor1d(array1,array2)
print(symmetric_diff)

[1 2 3 4 5 6]
