<a href="https://colab.research.google.com/github/poojakanchala/Edukroncodes7781/blob/main/retail_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Manually created array: [Store ID, Sales, Customers, Inventory, Returns]
retail_data = np.array([
    [1, 25000, 300, 1200, 10],
    [2, 32000, 450, 1500, 15],
    [3, 28000, 380, 1100, 8],
    [4, 41000, 500, 1600, 20],
    [5, 35000, 420, 1400, 12],
    [6, 27000, 360, 1300, 9],
    [7, 39000, 480, 1700, 18],
    [8, 30000, 400, 1250, 14],
    [9, 45000, 550, 1800, 25],
    [10, 33000, 410, 1450, 11]
])

print(retail_data)

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


In [4]:
#1. What is the **total revenue** generated across all stores?
retail_data[:,4].sum()

np.int64(142)

In [9]:
#2. Which store recorded the **highest sales**?
retail_data[:,1].argmax()+1

np.int64(9)

In [10]:
#3. Which store recorded the **lowest sales**?
retail_data[:,1].argmin()+1

np.int64(1)

In [17]:
#4. What is the **average daily sales** per store?
(retail_data[:,1]).mean()/10

np.float64(3350.0)

In [44]:
#5. How many stores achieved sales **above ₹35,000**?
retail_data[retail_data[:,1] > 35000].shape

(3, 5)

In [46]:
#6. Which store had the **highest customer footfall**?
retail_data[:,2].argmax()+1

np.int64(9)

In [31]:
#7. What is the **average number of customers** per store?
(retail_data[:,2]).mean()/10

np.float64(42.5)

In [42]:
#8. How many stores have **more than 450 customers**?
retail_data[retail_data[:,2] > 450].shape

(3, 5)

In [45]:
#9. Which store has the **lowest customer count**?
retail_data[:,2].argmin()+1

np.int64(1)

In [51]:
#10. Is there any store where **high sales do not correspond to high customers**?
sales = retail_data[:,1].mean()
customers = retail_data[:,2].mean()
val = retail_data[(retail_data[:,1] > sales) & (retail_data[:,2]< customers)]
val

array([[    5, 35000,   420,  1400,    12]])

In [52]:
#11. What is the **total inventory** across all stores?
retail_data[:,3].sum()

np.int64(14300)

In [55]:
#12. Which store has the **highest inventory stock**?
retail_data[:,3].argmax()+1

np.int64(9)

In [58]:
#13. How many stores have **inventory less than 1300 units**?
retail_data[retail_data[:,3] < 1300].shape

(3, 5)

In [59]:
#14. Which store has the **highest return rate** (returns ÷ inventory)?
(retail_data[:,4]/retail_data[:,3]).argmax()

np.int64(8)

In [63]:
#Which stores have **returns greater than 15 units**?
retail_data[retail_data[:,4] > 15]

array([[    4, 41000,   500,  1600,    20],
       [    7, 39000,   480,  1700,    18],
       [    9, 45000,   550,  1800,    25]])

In [70]:
#16. Is there a **positive correlation** between sales and customers?
sales = retail_data[:, 1]
customers = retail_data[:, 2]

print(np.corrcoef(sales, customers)[0,1])

0.9593636912502479


In [68]:
#17. Which store has **high customer visits but low sales**?
sales = retail_data[:,1].mean()
customers = retail_data[:,2].mean()
val = retail_data[(retail_data[:,1] < sales) & (retail_data[:,2]> customers)]
val

array([[    2, 32000,   450,  1500,    15]])

In [71]:
#18. Which store has **low customers but high sales**?
sales = retail_data[:,1].mean()
customers = retail_data[:,2].mean()
val = retail_data[(retail_data[:,1] > sales) & (retail_data[:,2]< customers)]
val

array([[    5, 35000,   420,  1400,    12]])

In [82]:
#19. How many stores have **sales per customer above ₹90**?
retail_data[((retail_data[:,1])/(retail_data[:,2])) > 90]

array([], shape=(0, 5), dtype=int64)

In [83]:
#20. Which stores could **benefit from customer acquisition campaigns** (low customers, high inventory)?
inventory = retail_data[:,3].mean()
customers = retail_data[:,2].mean()
val = retail_data[(retail_data[:,3] > inventory) & (retail_data[:,2]< customers)]
val

array([[   10, 33000,   410,  1450,    11]])

In [84]:
#21. If profit margin is **20% of sales**, what is the **profit per store**?
sales = retail_data[:,1]
profit_per_store = sales*0.20
profit_per_store

array([5000., 6400., 5600., 8200., 7000., 5400., 7800., 6000., 9000.,
       6600.])

In [86]:
#22. Which store has the **highest profit**?
sales = retail_data[:,1]
profit_per_store = sales*0.20
profit_per_store.argmax()+1

np.int64(9)

In [87]:
#23. Which store has the **lowest profit**?
sales = retail_data[:,1]
profit_per_store = sales*0.20
profit_per_store.argmin()+1

np.int64(1)

In [88]:
#24. If sales increase by **10% next month**, what are the **new sales figures**?
sales = retail_data[:, 1]
new_sales = sales * 1.10
new_sales

array([27500., 35200., 30800., 45100., 38500., 29700., 42900., 33000.,
       49500., 36300.])

In [89]:
#25. How will **total profit** change with the 10% sales increase?
sales = retail_data[:, 1]
new_sales = sales * 1.10
new_sales.sum()

np.float64(368500.0)

In [97]:
#26. Which stores need **inventory restocking** based on sales and current stock?
store_ids = retail_data[:, 0]
inventory = retail_data[:, 3]
sales = retail_data[:, 1]
restocking_stack = store_ids[inventory < sales]
restocking_stack



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [101]:
#27. Which stores show **high returns percentage** and might require **quality checks**?
store_ids = retail_data[:, 0]
sales = retail_data[:, 1]
returns = retail_data[:, 4]

returns_percentage = (returns / sales) * 100
average_return = returns_percentage.mean()
for i in range(len(store_ids)):
    if returns_percentage[i] > average_return:
      print(store_ids[i])

2
4
7
8
9


In [6]:
# 28. Which store is the **best performer overall** (sales, customers, inventory turnover)?




In [ ]:
#29. Which store is the **worst performer overall**?

In [ ]:
30. #Which stores can be considered for **expansion** based on strong sales and customer metrics?